import { Product } from "./types/Product"

export const sampleProducts: Product[] = [
    {
      id: 'sss-h',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '../images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '../images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Pants',
      slug: 'lacoste-free-pants',
      category: 'Pants',
      image: '../images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '../images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },

    {
      name: 'Ash-Checked-Shirt',
      slug: 'Ash-Checked-Shirt',
      category: 'Shirts',
      image: '../images/p6.jpg',
      price: 80,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 11,
      description: 'high quality product',
    },
    {
      name: 'Baige-Formal-Shirt',
      slug: 'Baige-Formal-Shirt',
      category: 'Shirts',
      image: '../images/p7.jpg',
      price: 79,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'White-Formal-Shirt',
      slug: 'White-Formal-Shirt',
      category: 'Shirts',
      image: '../images/p8.jpg',
      price: 250,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Black-Shirt',
      slug: 'Black-Shirt',
      category: 'Shirts',
      image: '../images/p9.jpg',
      price: 220,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 11,
      description: 'high quality product',
    },
    {
      name: 'Black-Short-Sleeve-Shirt',
      slug: 'Black-Short-Sleeve-Shirt',
      category: 'Shirts',
      image: '../images/p10.jpg',
      price: 200,
      countInStock: 11,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Stripe-Shirt',
      slug: 'Stripe-Shirt',
      category: 'Shirts',
      image: '../images/p11.jpg',
      price: 260,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'White-OverSized-Shirt',
      slug: 'White-OverSized-Shirt',
      category: 'Shirts',
      image: '../images/p12.jpg',
      price: 210,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 12,
      description: 'high quality product',
    },
    {
      name: 'Green-Short-Sleeve-Shirt',
      slug: 'Green-Short-Sleeve-Shirt',
      category: 'Shirts',
      image: '../images/p13.jpg',
      price: 200,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      name: 'Baige-StrightCut-Pant',
      slug: 'Baige-StrightCut-Pant',
      category: 'Pants',
      image: '../images/p14.jpg',
      price: 280,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 11,
      description: 'high quality product',
    },
    {
      name: 'Black-Loose-Pant',
      slug: 'Black-Loose-Pant',
      category: 'Pants',
      image: '../images/p15.jpg',
      price: 270,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 13,
      description: 'high quality product',
    },
    {
      name: 'Baige-Loose-Pant',
      slug: 'Baige-Loose-Pant',
      category: 'Pants',
      image: '../images/p16.jpg',
      price: 240,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Black-Cotton-pant',
      slug: 'Black-Cotton-Pant',
      category: 'Pants',
      image: '../images/p17.jpg',
      price: 200,
      countInStock: 16,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 14,
      description: 'high quality product',
    },
    
  ]
  