import bcrypt from 'bcryptjs'
import { Product } from "./models/productModel"
import { User } from "./models/userModel"

export const sampleProducts: Product[] = [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '../images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
      images: ['../images/p1.jpg'], // Add images array
    isFeatured: false, 
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
     image: '../images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
      images: ['../images/p2.jpg'], // Add images array
    isFeatured: false, // Add isFea
    },
    {
      name: 'Lacoste Free Pants',
      slug: 'lacoste-free-pants',
      category: 'Pants',
     image: '../images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
      images: ['../images/p3.jpg'], // Add images array
    isFeatured: false, // Add isFea
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '../images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
      images: ['../images/p4.jpg'], // Add images array
    isFeatured: false, // Add isFea
    },

    {
      name: 'Ash-Checked-Shirt',
      slug: 'Ash-Checked-Shirt',
      category: 'Shirts',
      image: '../images/p6.jpg',
      price: 80,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 11,
      description: 'High quality product',
      images: ['../images/p6.jpg'],
      isFeatured: false,
    },
    {
      name: 'Baige-Formal-Shirt',
      slug: 'Baige-Formal-Shirt',
      category: 'Shirts',
      image: '../images/p7.jpg',
      price: 79,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality product',
      images: ['../images/p7.jpg'],
      isFeatured: false,
    },
    {
      name: 'White-Formal-Shirt',
      slug: 'White-Formal-Shirt',
      category: 'Shirts',
      image: '../images/p8.jpg',
      price: 250,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 15,
      description: 'high quality product',
      images: ['../images/p8.jpg'],
      isFeatured: false,
    },
    {
      name: 'Black-Shirt',
      slug: 'Black-Shirt',
      category: 'Shirts',
      image: '../images/p9.jpg',
      price: 220,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 11,
      description: 'high quality product',
      images: ['../images/p9.jpg'],
      isFeatured: false,
    },
    {
      name: 'Black-Short-Sleeve-Shirt',
      slug: 'Black-Short-Sleeve-Shirt',
      category: 'Shirts',
      image: '../images/p10.jpg',
      price: 200,
      countInStock: 11,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      images: ['../images/p10.jpg'],
      isFeatured: false,
    },
    {
      name: 'Stripe-Shirt',
      slug: 'Stripe-Shirt',
      category: 'Shirts',
      image: '../images/p11.jpg',
      price: 260,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 15,
      description: 'high quality product',
      images: ['../images/p11.jpg'],
      isFeatured: false,
    },
    {
      name: 'White-OverSized-Shirt',
      slug: 'White-OverSized-Shirt',
      category: 'Shirts',
      image: '../images/p12.jpg',
      price: 210,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 12,
      description: 'high quality product',
      images: ['../images/p12.jpg'],
      isFeatured: false,
    },
    {
      name: 'Green-Short-Sleeve-Shirt',
      slug: 'Green-Short-Sleeve-Shirt',
      category: 'Shirts',
      image: '../images/p13.jpg',
      price: 200,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 8,
      description: 'high quality product',
      images: ['../images/pp13.jpg'],
      isFeatured: false,
    },
    {
      name: 'Baige-StrightCut-Pant',
      slug: 'Baige-StrightCut-Pant',
      category: 'Pants',
      image: '../images/p14.jpg',
      price: 280,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 11,
      description: 'high quality product',
      images: ['../images/p14.jpg'],
      isFeatured: false,
    },
    {
      name: 'Black-Loose-Pant',
      slug: 'Black-Loose-Pant',
      category: 'Pants',
      image: '../images/p15.jpg',
      price: 270,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 13,
      description: 'high quality product',
      images: ['../images/pp15.jpg'],
      isFeatured: false,
    },
    {
      name: 'Baige-Loose-Pant',
      slug: 'Baige-Loose-Pant',
      category: 'Pants',
      image: '../images/p16.jpg',
      price: 240,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 10,
      description: 'high quality product',
      images: ['../images/p16.jpg'],
      isFeatured: false,
    },
    {
      name: 'Black-Cotton-pant',
      slug: 'Black-Cotton-Pant',
      category: 'Pants',
      image: '../images/p17.jpg',
      price: 200,
      countInStock: 16,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 14,
      description: 'high quality product',
      images: ['../images/p17.jpg'],
      isFeatured: false,
    },
  ]
  
  export const sampleUsers: User[] = [
    {
      name: 'Joe',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ]